# Generated by Django 4.1.2 on 2022-10-23 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_estudiantes_estudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fechadeentrega',
            new_name='fecha_de_entrega',
        ),
    ]
